package consts

// OrderStatus ...
type OrderStatus string

const (
	// OrderStatusWAITING ...
	OrderStatusWAITING = OrderStatus("WAITING")
	// OrderStatusORDERED ...
	OrderStatusORDERED = OrderStatus("ORDERED")
	// OrderStatusMODIFYING ...
	OrderStatusMODIFYING = OrderStatus("MODIFYING")
	// OrderStatusCANCELLING ...
	OrderStatusCANCELLING = OrderStatus("CANCELLING")
	// OrderStatusCANCELED ...
	OrderStatusCANCELED = OrderStatus("CANCELED")
	// OrderStatusEXECUTED ...
	OrderStatusEXECUTED = OrderStatus("EXECUTED")
	// OrderStatusEXPIRED ...
	OrderStatusEXPIRED = OrderStatus("EXPIRED")
)
