package consts

// WebSocketChannel ...
type WebSocketChannel string

const (
	// WebSocketChannelTicker ...
	WebSocketChannelTicker = WebSocketChannel("ticker")
	// WebSocketChannelOrderBooks ...
	WebSocketChannelOrderBooks = WebSocketChannel("orderbooks")
	// WebSocketChannelTrades ...
	WebSocketChannelTrades = WebSocketChannel("trades")
	// WebSocketChannelExecutionEvents ...
	WebSocketChannelExecutionEvents = WebSocketChannel("executionEvents")
	// WebSocketChannelOrderEvents ...
	WebSocketChannelOrderEvents = WebSocketChannel("orderEvents")
	// WebSocketChannelPositionEvents ...
	WebSocketChannelPositionEvents = WebSocketChannel("positionEvents")
	// WebSocketChannelPositionSummaryEvents ...
	WebSocketChannelPositionSummaryEvents = WebSocketChannel("positionSummaryEvents")
)
